import createClient from 'openapi-fetch';
import type { paths } from './openapi-paths'; // generated by openapi-typescript

export const client = createClient<paths>({
	baseUrl: 'https://f06kj1k332.execute-api.ap-southeast-2.amazonaws.com/dev/'
});

export const tryGetFromCache = async (url: string, options: object) => {
	const cache = await caches.open('api-cache');
	const hash = btoa(JSON.stringify({ url, options }));
	const request = new Request(document.location.origin + '/api-cache/' + hash);
	const response = await cache.match(request);
	if (response) {
		const { data, expireAt } = await response.json();
		if (expireAt === -1 || expireAt > Date.now()) {
			return data;
		}
		await cache.delete(request);
	}
	return null;
};

export const setCache = async (
	url: string,
	options: object,
	data: object,
	expireAt: number = -1 // -1 means never expire
) => {
	const cache = await caches.open('api-cache');
	const hash = btoa(JSON.stringify({ url, options }));
	const request = new Request(document.location.origin + '/api-cache/' + hash);
	const response = new Response(JSON.stringify({ data, expireAt }));
	await cache.put(request, response);
};
