import createClient from 'openapi-fetch';
import type { paths } from './openapi-paths'; // generated by openapi-typescript
import { config } from '$lib/config';

export const client = createClient<paths>({
	baseUrl: config.apiUrls.ddpDonations
});
