/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/donations/users": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List all users who have made donations (requires token from AAO API) */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of users who have made donations */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            users?: string[];
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/donations/{user_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List the donations made by a user */
        get: {
            parameters: {
                query?: {
                    /** @description The platform to filter donations by (e.g., facebook, instagram, etc.) */
                    platform?: string;
                };
                header?: never;
                path: {
                    /** @description The ID of the user whose donations are being retrieved */
                    user_id: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description A list of donations made by the user */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            donations?: components["schemas"]["Donation"][];
                        };
                    };
                };
            };
        };
        put?: never;
        /** Create a new donation for a user on a specific platform. Only accepts JSON files. */
        post: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    user_id: string;
                };
                cookie?: never;
            };
            /** @description Donation details */
            requestBody: {
                content: {
                    "application/json": {
                        /**
                         * @description The platform where the donation was made (e.g., facebook, instagram, etc.)
                         * @example facebook
                         */
                        platform?: string;
                        files?: {
                            /**
                             * @description The name of the file associated with the donation
                             * @example example.json
                             */
                            file_name?: string;
                            /**
                             * @description The content of the file, typically a JSON object
                             * @example {
                             *       "key": "value"
                             *     }
                             */
                            content?: Record<string, never>;
                        }[];
                    };
                };
            };
            responses: {
                /** @description Donation created successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Success message
                             * @example Donation created successfully
                             */
                            message?: string;
                            /**
                             * @description Indicates if the donation was created successfully
                             * @example true
                             */
                            success?: boolean;
                            donation?: {
                                /**
                                 * @description The ID of the donation
                                 * @example ABF5C8/facebook/1633036800
                                 */
                                id?: string;
                                /**
                                 * @description The platform where the donation was made
                                 * @example facebook
                                 */
                                platform?: string;
                                /**
                                 * @description The timestamp of the donation
                                 * @example 1633036800
                                 */
                                timestamp?: number;
                                files?: string[];
                            };
                        };
                    };
                };
                /** @description Bad request, invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Invalid input data
                             */
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Internal server error
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/donations/{user_id}/{platform}/{timestamp}/{file_name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get a specific donation file for a user */
        get: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the user whose donation file is being retrieved */
                    user_id: string;
                    /** @description The platform where the donation was made (e.g., facebook, instagram, etc.) */
                    platform: string;
                    /** @description The timestamp of the donation file */
                    timestamp: string;
                    /** @description The name of the file to retrieve (e.g., example.json) */
                    file_name: string;
                };
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description The requested donation file */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": Record<string, never>;
                    };
                };
                /** @description File not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example File not found
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/donations/{user_id}/{platform}/{timestamp}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete specific files from a user's donation */
        delete: {
            parameters: {
                query?: never;
                header?: never;
                path: {
                    /** @description The ID of the user whose donation files are being deleted */
                    user_id: string;
                    /** @description The platform where the donation was made (e.g., facebook, instagram, etc.) */
                    platform: string;
                    /** @description The timestamp of the donation files to delete */
                    timestamp: string;
                };
                cookie?: never;
            };
            requestBody: {
                content: {
                    "application/json": {
                        /** @description List of file names to delete from the donation (e.g., ["example.json"]) */
                        file_names?: string[];
                    };
                };
            };
            responses: {
                /** @description Files deleted successfully */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Success message
                             * @example Files deleted successfully
                             */
                            message?: string;
                        };
                    };
                };
                /** @description Bad request, invalid input data */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Invalid input data
                             */
                            error?: string;
                        };
                    };
                };
                /** @description Donation not found */
                404: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Donation not found
                             */
                            error?: string;
                        };
                    };
                };
                /** @description Internal server error */
                500: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content: {
                        "application/json": {
                            /**
                             * @description Error message
                             * @example Internal server error
                             */
                            error?: string;
                        };
                    };
                };
            };
        };
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/hello": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get: {
            parameters: {
                query?: never;
                header?: never;
                path?: never;
                cookie?: never;
            };
            requestBody?: never;
            responses: {
                /** @description OK */
                200: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
                /** @description Bad Request */
                400: {
                    headers: {
                        [name: string]: unknown;
                    };
                    content?: never;
                };
            };
        };
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** Donation */
        Donation: {
            /** Id */
            id: string;
            /** Platform */
            platform: string;
            /** Timestamp */
            timestamp: number;
            /** Files */
            files: string[];
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export type operations = Record<string, never>;
